---
- name: install apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: cp index file
  ansible.builtin.copy:
    src: /home/ubuntu/role1/files/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

